insert into movie_content_items (
  id,
  slug,
  title,
  synopsis,
  genres,
  year,
  duration_minutes,
  maturity_rating,
  cloudflare_stream_uid,
  requires_signed_playback
)
values
  (
    'content-001',
    'the-last-kickoff',
    'The Last Kickoff',
    'A retiring striker gets one final chance at continental glory while mentoring a rising academy star.',
    array['Sports', 'Drama'],
    2026,
    122,
    '13+',
    null,
    false
  ),
  (
    'content-002',
    'silent-grid',
    'Silent Grid',
    'When a citywide blackout knocks out mobile networks, a gamer-led crew uses analog radio and street maps to restore communications.',
    array['Sci-Fi', 'Thriller'],
    2025,
    110,
    '16+',
    null,
    false
  ),
  (
    'content-003',
    'market-day',
    'Market Day',
    'A food vendor and a radio producer build a surprise local hit show while trying to keep a crowded market together.',
    array['Drama', 'Comedy'],
    2024,
    101,
    '13+',
    null,
    false
  )
on conflict (id) do nothing;

insert into iptv_catalog_items (
  id,
  parent_id,
  kind,
  title,
  slug,
  synopsis,
  badge,
  genres,
  release_year,
  duration_minutes,
  maturity_rating,
  channel_number,
  is_featured,
  available_from,
  metadata
)
values
  (
    'live-arena-1',
    null,
    'live_channel',
    'Arena 1',
    'arena-1',
    'Primary live channel slot for sports nights, premium fixtures, and marquee event windows.',
    'LIVE',
    array['Live TV', 'Sports'],
    null,
    null,
    null,
    101,
    true,
    null,
    jsonb_build_object('region', 'Kenya', 'note', 'Attach a licensed sports or event feed in Supabase playback sources.')
  ),
  (
    'live-cinema',
    null,
    'live_channel',
    'Cinema HD',
    'cinema-hd',
    'A curated live movie channel slot for studio-licensed movie rotations and premieres.',
    'HD',
    array['Live TV', 'Movies'],
    null,
    null,
    null,
    202,
    true,
    null,
    jsonb_build_object('region', 'Global')
  ),
  (
    'live-series',
    null,
    'live_channel',
    'Series Central',
    'series-central',
    'Always-on channel for episodic drops, box sets, and binge-friendly daily blocks.',
    '24/7',
    array['Live TV', 'Series'],
    null,
    null,
    null,
    305,
    false,
    null,
    '{}'::jsonb
  ),
  (
    'sports-ucl-night',
    null,
    'sports_event',
    'UEFA Champions League Night',
    'uefa-champions-league-night',
    'Reserved event slot for licensed Champions League coverage. Add the approved provider feed to make this watchable.',
    'UCL',
    array['Football', 'Live Sports'],
    null,
    null,
    null,
    null,
    true,
    timezone('utc', now()) + interval '3 days',
    jsonb_build_object('rightsRequired', true)
  ),
  (
    'movie-last-kickoff',
    null,
    'movie',
    'The Last Kickoff',
    'the-last-kickoff',
    'A retiring striker gets one final chance at continental glory while mentoring a rising academy star.',
    'New',
    array['Sports', 'Drama'],
    2026,
    122,
    '13+',
    null,
    true,
    null,
    jsonb_build_object('cloudflareEnv', 'CF_STREAM_UID_LAST_KICKOFF')
  ),
  (
    'movie-silent-grid',
    null,
    'movie',
    'Silent Grid',
    'silent-grid',
    'When a citywide blackout knocks out mobile networks, a gamer-led crew uses analog radio and street maps to restore communications.',
    null,
    array['Sci-Fi', 'Thriller'],
    2025,
    110,
    '16+',
    null,
    true,
    null,
    jsonb_build_object('cloudflareEnv', 'CF_STREAM_UID_SILENT_GRID')
  ),
  (
    'movie-market-day',
    null,
    'movie',
    'Market Day',
    'market-day',
    'A food vendor and a radio producer build a surprise local hit show while trying to keep a crowded market together.',
    null,
    array['Drama', 'Comedy'],
    2024,
    101,
    '13+',
    null,
    false,
    null,
    jsonb_build_object('cloudflareEnv', 'CF_STREAM_UID_MARKET_DAY')
  ),
  (
    'series-pulse-city',
    null,
    'series',
    'Pulse City',
    'pulse-city',
    'A fast-moving Nairobi newsroom turns late-night tips into headline stories while holding together a family-owned station.',
    'Series',
    array['Drama', 'Newsroom'],
    2026,
    null,
    '13+',
    null,
    true,
    null,
    jsonb_build_object('seasons', 1)
  ),
  (
    'pulse-city-s1e1',
    'series-pulse-city',
    'episode',
    'Pulse City: Episode 1',
    'pulse-city-s1e1',
    'The station lands a story that could double the audience or sink the business.',
    null,
    array['Drama'],
    2026,
    48,
    '13+',
    null,
    false,
    null,
    jsonb_build_object('seasonNumber', 1, 'episodeNumber', 1)
  ),
  (
    'pulse-city-s1e2',
    'series-pulse-city',
    'episode',
    'Pulse City: Episode 2',
    'pulse-city-s1e2',
    'A leaked clip forces the team into a live-broadcast gamble.',
    null,
    array['Drama'],
    2026,
    46,
    '13+',
    null,
    false,
    null,
    jsonb_build_object('seasonNumber', 1, 'episodeNumber', 2)
  )
on conflict (id) do update
set
  parent_id = excluded.parent_id,
  kind = excluded.kind,
  title = excluded.title,
  slug = excluded.slug,
  synopsis = excluded.synopsis,
  badge = excluded.badge,
  genres = excluded.genres,
  release_year = excluded.release_year,
  duration_minutes = excluded.duration_minutes,
  maturity_rating = excluded.maturity_rating,
  channel_number = excluded.channel_number,
  is_featured = excluded.is_featured,
  available_from = excluded.available_from,
  metadata = excluded.metadata;

insert into iptv_live_events (
  item_id,
  competition,
  home_team,
  away_team,
  starts_at,
  venue,
  status,
  metadata
)
values
  (
    'sports-ucl-night',
    'UEFA Champions League',
    'Home Team',
    'Away Team',
    timezone('utc', now()) + interval '3 days',
    'Provider-defined venue',
    'scheduled',
    jsonb_build_object('note', 'Configure a rights-cleared live source before exposing this slot.')
  )
on conflict (item_id) do update
set
  competition = excluded.competition,
  home_team = excluded.home_team,
  away_team = excluded.away_team,
  starts_at = excluded.starts_at,
  venue = excluded.venue,
  status = excluded.status,
  metadata = excluded.metadata;
