[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "pnpm run build"
  functions = ".netlify/functions-internal"

  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,TMDB_API_BASE_URL,TMDB_IMAGE_BASE_URL,TMDB_API_LANGUAGE,IPTV_PROVIDER_NAME,IPTV_PROVISIONING_MODE,MPESA_ENVIRONMENT,COMPATIBLE_PLAYER_BASE_URL,COMPATIBLE_PLAYER_COLOR,COMPATIBLE_PLAYER_NEXT_EPISODE,COMPATIBLE_PLAYER_EPISODE_SELECTOR,COMPATIBLE_PLAYER_AUTOPLAY_NEXT_EPISODE,COMPATIBLE_PLAYER_OVERLAY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
