// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/accessories" | "/admin" | "/admin/iptv" | "/admin/login" | "/blog" | "/blog/[slug]" | "/careers" | "/cart" | "/checkout" | "/consoles" | "/contact" | "/deals" | "/digital-store" | "/games" | "/iptv" | "/iptv/my-subscription" | "/iptv/subscribe/[planId]" | "/live" | "/movies" | "/movies/film/[id]" | "/movies/login" | "/movies/watch/[slug]" | "/nintendo-switch" | "/orders" | "/pc-gaming" | "/playstation" | "/pre-owned" | "/privacy-policy" | "/return-policy" | "/terms-of-service" | "/trading-cards" | "/warranty" | "/xbox"
type AppRouteHandlerRoutes = "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/codes" | "/api/admin/impersonate" | "/api/admin/iptv" | "/api/admin/iptv/assign" | "/api/admin/iptv/grant" | "/api/admin/team" | "/api/iptv/confirm" | "/api/iptv/live" | "/api/iptv/lookup" | "/api/iptv/repo-playlists" | "/api/iptv/stream/[subscriptionId]/playlist.m3u" | "/api/iptv/subscribe" | "/api/movies/auth/login" | "/api/movies/auth/logout" | "/api/mpesa/callback" | "/api/mpesa/status" | "/api/mpesa/stk-push" | "/api/tmdb"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/accessories": {}
  "/admin": {}
  "/admin/iptv": {}
  "/admin/login": {}
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/codes": {}
  "/api/admin/impersonate": {}
  "/api/admin/iptv": {}
  "/api/admin/iptv/assign": {}
  "/api/admin/iptv/grant": {}
  "/api/admin/team": {}
  "/api/iptv/confirm": {}
  "/api/iptv/live": {}
  "/api/iptv/lookup": {}
  "/api/iptv/repo-playlists": {}
  "/api/iptv/stream/[subscriptionId]/playlist.m3u": { "subscriptionId": string; }
  "/api/iptv/subscribe": {}
  "/api/movies/auth/login": {}
  "/api/movies/auth/logout": {}
  "/api/mpesa/callback": {}
  "/api/mpesa/status": {}
  "/api/mpesa/stk-push": {}
  "/api/tmdb": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/careers": {}
  "/cart": {}
  "/checkout": {}
  "/consoles": {}
  "/contact": {}
  "/deals": {}
  "/digital-store": {}
  "/games": {}
  "/iptv": {}
  "/iptv/my-subscription": {}
  "/iptv/subscribe/[planId]": { "planId": string; }
  "/live": {}
  "/movies": {}
  "/movies/film/[id]": { "id": string; }
  "/movies/login": {}
  "/movies/watch/[slug]": { "slug": string; }
  "/nintendo-switch": {}
  "/orders": {}
  "/pc-gaming": {}
  "/playstation": {}
  "/pre-owned": {}
  "/privacy-policy": {}
  "/return-policy": {}
  "/terms-of-service": {}
  "/trading-cards": {}
  "/warranty": {}
  "/xbox": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
