// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accessories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessories">> = Specific
  const handler = {} as typeof import("../../src/app/accessories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/iptv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/iptv">> = Specific
  const handler = {} as typeof import("../../src/app/admin/iptv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/consoles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consoles">> = Specific
  const handler = {} as typeof import("../../src/app/consoles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deals">> = Specific
  const handler = {} as typeof import("../../src/app/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/digital-store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-store">> = Specific
  const handler = {} as typeof import("../../src/app/digital-store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games">> = Specific
  const handler = {} as typeof import("../../src/app/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/iptv/my-subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iptv/my-subscription">> = Specific
  const handler = {} as typeof import("../../src/app/iptv/my-subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/iptv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iptv">> = Specific
  const handler = {} as typeof import("../../src/app/iptv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/iptv/subscribe/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iptv/subscribe/[planId]">> = Specific
  const handler = {} as typeof import("../../src/app/iptv/subscribe/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live">> = Specific
  const handler = {} as typeof import("../../src/app/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/movies/film/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/movies/film/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/movies/film/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/movies/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/movies/login">> = Specific
  const handler = {} as typeof import("../../src/app/movies/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/movies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/movies">> = Specific
  const handler = {} as typeof import("../../src/app/movies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/movies/watch/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/movies/watch/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/movies/watch/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nintendo-switch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nintendo-switch">> = Specific
  const handler = {} as typeof import("../../src/app/nintendo-switch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pc-gaming/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pc-gaming">> = Specific
  const handler = {} as typeof import("../../src/app/pc-gaming/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/playstation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playstation">> = Specific
  const handler = {} as typeof import("../../src/app/playstation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pre-owned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pre-owned">> = Specific
  const handler = {} as typeof import("../../src/app/pre-owned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/return-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-policy">> = Specific
  const handler = {} as typeof import("../../src/app/return-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trading-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trading-cards">> = Specific
  const handler = {} as typeof import("../../src/app/trading-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warranty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warranty">> = Specific
  const handler = {} as typeof import("../../src/app/warranty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/xbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/xbox">> = Specific
  const handler = {} as typeof import("../../src/app/xbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/codes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/impersonate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/iptv/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/iptv/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/iptv/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/iptv/grant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/iptv/grant">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/iptv/grant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/iptv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/iptv">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/iptv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/team">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/live">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/lookup">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/repo-playlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/repo-playlists">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/repo-playlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/stream/[subscriptionId]/playlist.m3u/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/stream/[subscriptionId]/playlist.m3u">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/stream/[subscriptionId]/playlist.m3u/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/iptv/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iptv/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/iptv/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/movies/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movies/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/movies/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/movies/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movies/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/movies/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mpesa/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mpesa/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/mpesa/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mpesa/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mpesa/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/mpesa/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mpesa/stk-push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mpesa/stk-push">> = Specific
  const handler = {} as typeof import("../../src/app/api/mpesa/stk-push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tmdb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tmdb">> = Specific
  const handler = {} as typeof import("../../src/app/api/tmdb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
